services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      - "GF_PANELS_DISABLE_SANITIZE_HTML=true"
    volumes:
      - ./metrics/grafana/storage:/var/lib/grafana
  db:
    image: mysql:8.2.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - "./petrol-api/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql"
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

  petrol-api:
    build: petrol-api
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - db
      - otel-collector
      - rabbitmq
    healthcheck:
      test: curl -f http://petrol-api:8080/stations/aggregate/PROVINCE || exit 1
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 5

  petrol-reports:
    build: petrol-reports
    ports:
      - "5000:5000"
    depends_on:
      petrol-api:
        condition: service_healthy
        restart: true

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.90.1
    command: --config=/etc/otelcol-contrib/config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"

  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"
    depends_on:
      - otel-collector

  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./metrics/prometheus/storage:/prometheus
    ports:
      - "9090:9090"

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.15.1
    command:
      - "--mysqld.username=root:my-secret-pw"
      - "--mysqld.address=db:3306"
      - "--collect.info_schema.processlist"
      - "--collect.info_schema.innodb_metrics"
      - "--collect.info_schema.tablestats"
      - "--collect.info_schema.tables"
      - "--collect.info_schema.userstats"
      - "--collect.engine_innodb_status"
    ports:
      - "9104:9104"
