receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    verbosity: detailed
  # TODO: maybe use Grafana tempo (or both for testing?)
  # https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/otel-collector.yaml
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Data sources: metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging,prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    logs:
      receivers: [otlp]
      exporters: [logging]