CREATE DATABASE petrolstations CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
USE petrolstations;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS regions (
    region_code VARCHAR(255) PRIMARY KEY,
    region_name VARCHAR(255) NOT NULL
);

INSERT INTO regions (region_code, region_name) VALUES
    ('02', 'Albacete'),
    ('03', 'Alicante'),
    ('04', 'Almería'),
    ('01', 'Álava'),
    ('33', 'Asturias'),
    ('05', 'Ávila'),
    ('06', 'Badajoz'),
    ('07', 'Islas Baleares'),
    ('08', 'Barcelona'),
    ('48', 'Bizkaia'),
    ('09', 'Burgos'),
    ('10', 'Cáceres'),
    ('11', 'Cádiz'),
    ('39', 'Cantabria'),
    ('12', 'Castellón'),
    ('51', 'Ceuta'),
    ('13', 'Ciudad Real'),
    ('14', 'Córdoba'),
    ('15', 'A Coruña'),
    ('16', 'Cuenca'),
    ('20', 'Gipuzkoa'),
    ('17', 'Girona'),
    ('18', 'Granada'),
    ('19', 'Guadalajara'),
    ('21', 'Huelva'),
    ('22', 'Huesca'),
    ('23', 'Jaén'),
    ('24', 'León'),
    ('27', 'Lugo'),
    ('25', 'Lleida'),
    ('28', 'Madrid'),
    ('29', 'Málaga'),
    ('52', 'Melilla'),
    ('30', 'Murcia'),
    ('31', 'Navarra'),
    ('32', 'Ourense'),
    ('34', 'Palencia'),
    ('35', 'Las Palmas'),
    ('36', 'Pontevedra'),
    ('26', 'La Rioja'),
    ('37', 'Salamanca'),
    ('38', 'Santa Cruz de Tenerife'),
    ('40', 'Segovia'),
    ('41', 'Sevilla'),
    ('42', 'Soria'),
    ('43', 'Tarragona'),
    ('44', 'Teruel'),
    ('45', 'Toledo'),
    ('46', 'Valencia'),
    ('47', 'Valladolid'),
    ('49', 'Zamora'),
    ('50', 'Zaragoza');